AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
    Function:
        Runtime: nodejs12.x
        Timeout: 120
        MemorySize: 256
        Handler: index.handler
        Tracing: Active
    Api:
      EndpointConfiguration: REGIONAL
      TracingEnabled: true

Resources:
    TimeLoggerFunction:
        Type: AWS::Serverless::Function
        Properties:
          CodeUri: ./src/TimeFunction
          Events:
            ApiEvent:
              Type: Api
              Properties:
                Path: /
                Method: get
                RestApiId:
                  Ref: TimeApi
          Timeout: 60
            # ApiEvent:
            #     Type: HttpApi
            #     Properties:
            #         ApiId: !Ref TimeApi
            #         Method: GET
            #         Path: /time

    TimeApi:
      Type: AWS::Serverless::Api
      Properties:
        Name: TimeApi
        StageName: prod
        Cors: "'*'"

    TimeLoggerFunctionPermission:
        Type: AWS::Lambda::Permission
        DependsOn:
            - TimeApi
        Properties:
            Action: lambda:InvokeFunction
            FunctionName: !Ref TimeLoggerFunction
            Principal: apigateway.amazonaws.com
